# Commands to start on workspace startup
tasks:
  - name: Install Pipedream CLI
    command: curl https://cli.pipedream.com/install | sudo sh
  - name: Set up API KEY
    command: mkdir ~/.config/pipedream && echo "api_key = $PIPEDREAM_API_KEY" > ~/.config/pipedream/config
